### PR TITLE
add map to messages + move message into component

### PR DESCRIPTION
**Pull request by kjoscha**

### CODE REVIEW

**Comment by kjoscha** [comment]
please review

**Comment by 0x46616c6b** [comment]
Hey, you need to update your branch first. I changed package management from npm to yarn.

**Comment by 0x46616c6b** [comment]
grafik

I would suggest to use a Button here instead of a new line in the Card Component with a radio Button.

**Comment by kjoscha** [comment]
I changed it to a very simple icon with tooltip on hover. Furthermore, I added props validation to the new component

**Comment by 0x46616c6b** [comment]
Nice! Looks good to me

**Pull request merged**
